# Generated by Django 4.0 on 2021-12-22 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_image_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='title',
        ),
    ]
