# Generated by Django 4.0 on 2021-12-22 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_image_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='updates',
            new_name='updated',
        ),
    ]
