# Generated by Django 4.0 on 2021-12-23 11:57

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_updates_image_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='histogram',
            field=django_mysql.models.ListCharField(models.CharField(max_length=20), default=[], max_length=66, size=None),
        ),
    ]
