# Generated by Django 4.0 on 2021-12-23 12:21

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_image_histogram'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='histogram',
            field=django_mysql.models.ListTextField(models.CharField(max_length=25), default=[], size=None),
        ),
    ]
