# Generated by Django 4.0 on 2021-12-23 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_image_histogram'),
    ]

    operations = [
        migrations.CreateModel(
            name='Distance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_corr', models.FloatField()),
                ('d_inter', models.FloatField()),
                ('d_chi', models.FloatField()),
                ('d_hell', models.FloatField()),
                ('img1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='img1', to='api.image')),
                ('img2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='img2', to='api.image')),
            ],
        ),
    ]
