# Generated by Django 4.0 on 2021-12-23 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_distance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='distance',
            old_name='d_hell',
            new_name='d_bhatt',
        ),
    ]
