# Generated by Django 4.0 on 2021-12-24 00:26

from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('histogram', django_mysql.models.ListTextField(models.CharField(max_length=25), default=[], size=None)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Distance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_corr', models.FloatField(null=True)),
                ('d_inter', models.FloatField(null=True)),
                ('d_chi', models.FloatField(null=True)),
                ('d_bhatt', models.FloatField(null=True)),
                ('img1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='img1', to='api.image')),
                ('img2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='img2', to='api.image')),
            ],
        ),
    ]
